name: sortirin
description: "Sortirin — Gamifikasi pemilahan sampah berbasis reward nyata"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # State & DI
  get: ^4.6.6

  # Supabase
  supabase_flutter: ^2.8.0

  # Kamera (in-app only, no gallery)
  camera: ^0.11.0

  # Kompresi video
  video_compress: ^3.1.0

  # Hive (offline queue & cache)
  hive_flutter: ^1.1.0

  # Firebase Core
  firebase_core: ^3.12.0

  # Notifikasi
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^18.0.0

  # Kriptografi (SHA-256)
  crypto: ^3.0.0

  # GPS
  geolocator: ^13.0.0

  # HTTP
  dio: ^5.7.0

  # Device fingerprint
  device_info_plus: ^11.0.0

  # Icons
  cupertino_icons: ^1.0.8

  # .env loader
  flutter_dotenv: ^5.2.1

  # URL launcher (for OAuth redirect)
  url_launcher: ^6.3.0

  # OAuth types (re-exported by supabase)
  gotrue: ^2.20.0

  # Supabase Storage types (transitive dep, needed for FileOptions)
  storage_client: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
